### ISSUE TITLE
13 sources or 11 sources of data

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#104]
Just occurred to me that we really have 11 sources, not 13 as it says on the homepage:

GWAS Catalog
UniProt
European Variation Archive (EVA)
Gene2Phenotype
The Cancer Gene Census
IntOGen
ChEMBL
Reactome
Expression Atlas
Europe PMC
Phenodigm

UniProt literature is still UniProt.

**Comment by emepyc** [comment]
Strictly speaking you are right. We count **eva_somatic** and **uniprot_literature** as 2 datasources.

The [homepage](https://www.targetvalidation.org) is taking the information directly from the [API's stats method](http://targetvalidation.org/api/latest/public/utils/stats), which in my opinion is the best way [1].
_If_ we want to fix this, we have to think what is the best way to do it.

[1] - because it supports extra datasources in our partners (GSK) without any change in the webapp cod or config files and it prevents the webapp and the rest api to become out-of-sync

**Comment by emepyc** [comment]
If we want to keep using the API for this, we should fix this number (or make the aggregation of sources) in the API.
It would be weak to patch this in the frontend.

**Comment by emepyc** [comment]
Issue moved to [opentargets/rest_api #125](https://github.com/opentargets/rest_api/issues/125) via [**ZenHub**](https://www.zenhub.com/)
