### ISSUE TITLE
viz for GO on the target profile

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#119]
Followed our quick discussion on visualising GO terms in the target profile page, I could not find the viz in Ensembl Plants any more (they may have removed it). But it looked very much like this:

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0010150#term=ancchart

Not particularly pretty but perhaps better than the current status with a list of term descriptions only.

**Comment by andrewhercules** [comment]
Would be great to do this, but unfortunately we cannot visualise GO terms within the Platform for two key reasons:

1) The API doesn't return the graph and so the front-end cannot render the terms in relation to each other. At the moment, the API just returns a flat list of terms with the parent category.
2) Other resources that visualise terms within the graph (e.g. EBI QuickGO) cannot be embedded into the Platform due to layout and technical constraints. For more information, see the [18.06 front-end release plan](https://docs.google.com/document/d/1UyWfsE31Wi5VgMTcYEuEDLMcMmqGpyf4rjUuRrQ2Yv4/edit)
