### ISSUE TITLE
picasso panel: number of drugs highlighted

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#130]
People at Dundee workshop were confused with the number of drugs in phase IV displayed in the Picasso panel.

Once they move on to the association page and see in the facet “Drugs (9)” and got confused with the previous number of 12 in the Picasso panel (for tuberculosis for example). 

More confusion with that number arose from this example:

EFO_0003060: 37 number of drugs phase IV. In the definition of the disease it says it is divided in subtypes (based on the histology of the tumour, including ADENOCARCINOMA). When searching for ADENOCARCINOMA  (one of the subtypes), the picasso panel highlights ADENOCARCINOMA contains more drugs than the original EFO_0003060.

Perhaps the reason is that the subtype should be non-small cell lung adenocarcinoma rather than adenocarcinoma, more general term????

At any rate, we wonder if this number is useful at all? And why phase IV only? It seems @gkos-bio & @nikiforosk have heard similar comments before...

Worth revisiting the picasso panel when time allows...

**Comment by nikiforosk** [comment]
I raised this (and a few other issues) in https://github.com/opentargets/webapp/issues/113

**Comment by andrewhercules** [comment]
Ticket identified for inclusion in the next micro-release and moved from `Icebox` to `Prioritised`.

Rather than having only phase IV drugs, can we update the panel to display the total number of drugs associated with either the disease or target? This would be similar to the summary visualisation found in the drug data table. So for example, after [searching for asthma](https://www.targetvalidation.org/search?src=q:asthma), the panel should show "66 associated drugs".
