### ISSUE TITLE
look and feel of batch search = look and feel of Open Targets | Library

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#147]
the title says it all.

The look and feel of the | Library site is really nice, neat and modern.

From what I seem to have heard in meetings, it's likely there will be more tools like from Open Targets Core team...

Perhaps we could have:
Open Targets | Batch search (with this page similar to the | Library??!?!?!)
Open Targets | Platform

**Comment by emepyc** [comment]
The batch search is not different from the main open targets platform, it is just another page in the same webapp (as the association page or the evidence page). It just happens to have a bit different styling, because we didn't expended much time styling it further.
The `Library` site, as the `Dorothea` site, are completely different sites written from scratch, both using a styling framework different from the main webapp.

**Comment by peatroot** [comment]
Closing as not a `webapp` action.
