### ISSUE TITLE
"target" & "disease" terms are not highlighted in text-mining evidence

### ISSUE THREAD

**Issue by ckongEbi** [opentargets/webapp#149]
@emepyc @iandunham Collating results from text-mining workshop, we see handful of entries, where "target" & "disease" terms are not highlighted . Can you have a look? Thanks!

few examples:
1) http://targetvalidation.org/evidence/ENSG00000159899/EFO_0000403
![screen shot 2017-07-04 at 23 59 33](https://user-images.githubusercontent.com/6169985/27844101-bc84b942-6114-11e7-8b4b-12a9d36e7dca.png)

2) http://targetvalidation.org/evidence/ENSG00000164400/EFO_0003782
![screen shot 2017-07-05 at 00 02 55](https://user-images.githubusercontent.com/6169985/27844129-381fc42a-6115-11e7-9768-528c3dae7960.png)

**Comment by emepyc** [comment]
I have just checked both cases...
In the first one, the sentence in the abstract is...
`In the case of diffuse large B-cell lymphomas (DLBCLs), BCL6 inhibitors are equally effective in suppressing both the GCB- and the more aggressive ABC-DLBCL subtypes, both of which require BCL6 to maintain their survival`
while the reported matched sentence in europePMC is slightly different:
`In the case of diffuse large B-cell lymphomas (DLBCL), BCL6 inhibitors are equally effective in suppressing both the germinal center B-cell (GCB)- and the more aggressive activated B-cell (ABC)-DLBCL subtypes, both of which require BCL6 to maintain their survival.`

This is a complex issue we have identified in the past. We get the matching sentences from EuropePMC, but they don't provide the full abstracts in their evidence strings. So we get the abstracts directly from their REST api live in the webapp. The problem is that the abstracts they use to create the evidence strings are not always exactly the same they report in the REST api because there may have been post-publishing edits. This prevents the webapp code to recognise these sentences in the abstract and we fail to highlight them.

We reported this issue to europePMC some time ago and they didn't give us a solution to this. It may be worth checking again (CK I can forward you the email conversation).

**Comment by emepyc** [comment]
just for completeness, in the second case, this is the matching sentence... `After intrathecal treatments, participants underwent standardized follow-up, which included clinical examinations, revised ALS Functional Rating Scale (ALSFRS-R) questionnaire, blood and CSF sampling, and MRI of the neuroaxis.` which doesn't appear in the abstract at all.

**Comment by apierleoni** [comment]
These cases will not be fixed for now.
We are not going to ask europepmc to provide the original abstract since it would substantially complicate the evidence submission and analysis flow. The number of abstracts not highlighted is quite small.

Il 5 lug 2017, 14:54 +0100, Miguel

**Comment by ckongEbi** [comment]
@emepyc @apierleoni  , thanks for the historical context of the issue, we leave it as it is.
