### ISSUE TITLE
Proposed codebase refactoring

### ISSUE THREAD

**Issue by peatroot** [opentargets/webapp#180]
## Overview
Following discussion with @emepyc and @LucaFumis, here is a brain-dump of the proposed refactoring of the webapp codebase. Since this affects many files, it should ideally be done when there are few complex branches being worked on.

## Proposed aims
* **To group by function rather than type.** Currently, the `partials` directory contains most `.html` files. It would be better to move html templates and pages to be adjacent to their javascript partners (eg. directives and controllers).
* **To have one `angular` item per file.** The `services.js`, `controllers.js` and `directives.js` files each contain multiple items, which would preferably be split out into one file each.
* **To consistently prefix `angular` items.** Use with `ot` instead of `cttv`.
* **Plugin grouping** Each plugin's directives and templates should be grouped into subfolders, like the facets.
* **To simplify JS file registration.** To not require each new `app/js` file to be registered explicitly by name in `webappFiles.js`.
* **To consistently name `angular` item files** The following structure is partially used; we should apply it everywhere (it can be checked with `eslint`):
  * Controller filenames have format `<kebab-case-name>-controller.js`, but item name is `<camelCaseName>Ctrl`
  * Directive filenames have format `<kebab-case-name>-directive.js`, but item name is `<camelCaseName>`
  * Directive templates have format `<kebab-case-name>.html`
  * Service filenames have format `<kebab-case-name>-service.js`, but item name is `<camelCaseName>`

**Comment by emepyc** [comment]
**historical comment on automatic js file registration**
The initial rationale of webappFiles.js and having to be explicit about required files was two fold:
1- To have a kind of manifesto of the files being used by the webapp.
2- To be able to "un-require" files without removing them (they may serve as future reference). This was specially useful in early days when the development moved very fast.
Because the built process doesn't take files not in webappFiles, those files didn't go to the final production files.
The potential issue is having deprecated files still in the repo because they are not imported and make no harm to the built files.
We changed the model in the plugins folder (every js file in that folder is imported by default) which has the potential issue of including (building) plugins not stated in the config file, but simplifies the process of creating new plugins for 3rd parties.

All this being said, I think that automatic js file registration is the way to go and having a cleaner source files tree (we have to make sure that we don't import deprecated files preferably by removing them from the repo)

**Comment by elipapa** [comment]
cc/ @PriyankaW for her information.
we should close as many open stale branches as possible.

**Comment by peatroot** [comment]
## Structure mapping
Currently, the `app` directory looks like:
```
build
config
css
directives
docs
facets
imgs
js
jspm_packages
partials
plugins
swfs
vendor
...
```

I suggest we start with combining the `js` and `partials` directories. Perhaps something like:
```
pages/
  <page-name>.html
  <page-name>-controller.js
  page-components/
    <page-specific-component>.html
    <page-specific-component>-directive.js
components/
  <common-component>.html
  <common-component>-directive.js
services/
  <service-name>-service.js
```

Thoughts?
