### ISSUE TITLE
Integration day feedback for expression facets

### ISSUE THREAD

**Issue by peatroot** [opentargets/webapp#203]
The feedback that follows was obtained at integration day on 11/10/17. This affects the expression facets, which are being developed on `expression-facets-hierarchyless` and `expression-facets-zscore` branches.

This is the ideal set of things to be fixed for the release.

## UI only
* [x] Add **targets** as a y-axis label on the histogram.
* [x] Ensure that each level (on the histogram) can be set by clicking anywhere up to the maximum height (ie. to make it easier to select small values). This should exclude the zero case.
* [ ] The data type **RNA expression** should be renamed **Differential expression**. This may need to be checked with more of the team.
* [x] Add a tooltip to each bar containing a summary statement including the count (eg. *Show targets with RNA expression at level 7 or above in any of the selected tissues.* **OR** *Show targets with tissue specificity at level 7 or above in any of the selected tissues.*).
* [x] Rename the facet **RNA expression specificity** to **RNA tissue specificity**.
* [ ] **Clear all** button leaves some checkboxes in unexpected state.
* [x] Add an explanation of specificity (perhaps with a `?` button) and perhaps binning.
* [x] Remove the target counts from the tissues list (as they mean something different to the expectations)

## General (may involve backend work)
* [ ] Consider cell type/tissue merge; is this what we want? How else would it be handled?
* [ ] Specify exact requirements of API, including:
  * [ ] Ensure consistency of [-1, 0, ...levels] meaning between specificity and baseline. Ie. -1 should mean we have no data at all for this gene; 0 should mean below the cutoff threshold (as suggested by Expression Atlas); 1-n are the reasonable values.
  * [ ] Ensure matching numbers between (1) the filter count before clicking and (2) the target count in the title after clicking.
  * [ ] Ensure the histogram bar counts are consistent with the target count in the title before/after clicking.
  * [ ] Fix the lung/level 9 issue (ie. on the asthma associations page with baseline, select lung, then select level 9; the new page has **unexpectedly** no results).

**Comment by iandunham** [comment]
What does this one mean "Consider cell type/tissue merge"?

**Comment by peatroot** [comment]
One of the users found it confusing that cell types and tissues were all together and suggested splitting the categories in the UI. It is recorded mainly so as not to forget the feedback.

**Comment by emepyc** [comment]
Another issue with the current facets that we need to clarify probably at the data level. If you go to this example: https://expression-facets-zscore--paratrooper-antelope-70721.netlify.com/disease/EFO_0000270/associations?fcts=datatype:known_drug
and expand the "Heart" organ the numbers say that there are 42 genes expressed in the Heart and 49 expressed in the "coronary artery", which seems a bit odd

**Comment by emepyc** [comment]
Regarding the General section we need to decide the final configuration of the expression facet. It looks like having slight modifications on the data aggregations have a great impact in the amount of work to organise the data in the backend, so I wouldn't try to make any more steps and define what we want to have in the end.
Some of the decisions (to agree if they are feasible in the backend as well) we have to make are:

- baseline expression vs specificity: The api now allows to make both types of filters at the same time, but we need to make sure we want to have both options and we can do it in a way it is not confusing. If the main case of the baseline expression is to know "which genes are expressed in my tissue of interest", can this be achieved with the specificity facet? for example, clicking on a tissue with low specificity selected should give all genes expressed in the tissue without specificity restrictions.

- one general histogram / one histogram per tissue: If the latter, we need to allow the association endpoint to specify all these cases.

- AND / OR behaviour: Users showed a preference of AND vs OR, but this would be inconsistent with the other facets, is that a problem? can we have both behaviours in a way is easy to interpret?

- NOT logic: In the current implementation is not possible to have negative filters (NOT expressed in the brain) for example. This is an important use case in safety for example. Should we consider that option or not? (again, can we have this logic in the api?).

**Comment by emepyc** [comment]
After discussing all these issues and feedback we have agreed on:

1) To include in the upcoming release:
- The specificity facet for the next release with the few improvements / changes summarised in the UI section of this issue (see above)
- [Possibly] fix the counts in the specificity histogram (including only the targets included in any selected tissue instead of all the tissues in all resulting targets).

2) After the release we will work on a second iteration following the updated specifications allowed here: https://github.com/opentargets/webapp/blob/expression-facets-hierarchyless/specs/rna_expression_spec.md

3) We will create an interactive mock to test with users before all the changes required in the spec are implemented

**Comment by nikiforosk** [comment]
As discussed yesterday, for this release I'd recommend:
- Name the filter "Tissue RNA expression" without mentioning specificity. 
- Show the targets expressed in a tissue (e.g. lung) once "lung" is selected in the filter.
- Show the specificity histogram once the tissue is selected (so that people can filter down to particular levels of specificity for the set of targets expressed e.g. in lung).

Feel free to ignore this if it already captured elsewhere (It wasn't clear to me that it was but I might be wrong). I hope these are technically feasible for the first release.

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #20](https://github.com/opentargets/platform/issues/20) via [**ZenHub**](https://www.zenhub.com/)
