### ISSUE TITLE
association score of 0 but evidence > 0

### ISSUE THREAD

**Issue by emepyc** [opentargets/webapp#213]
We currently have evidence (rna expression) that doesn't add to the association score. This has several implications...

1) Since the flower is based on association scores, we have situations where the rna expression section has data but the petal is greyed out (in the evidence page)

2) Since the cells in the associations tables are based on association scores, we may want to differentiate between (white) cells having data and (white) cells not having data

**Comment by LucaFumis** [comment]
The approach taken in the flower could be adapted slightly and perhaps applied to the heatmaps too.
Currently we have
*score==0* : the petal is empty with a grey outline
*score>0* : the petal has a fill proportional to the score *and* a blue outline (this was introduced to not miss very low scores).

Could be modified to have:
*no data* : the petal is empty with a grey outline
*score>=0* : the petal has a fill proportional to the score *and* a blue outline.
So a score of 0 is captured by an empty petal with a blue outline.

Same could be applied to the cells in the heatmap?

What do you think @andrewhercules and @peatroot ?

**Comment by andrewhercules** [comment]
@LucaFumis - that's a great idea as I noticed that with some associations (e.g. https://www.targetvalidation.org/evidence/ENSG00000157764/EFO_0000221), we have the same issue. Just to make the design easier to implement, when the score >= 0, the text can be black rather than grey. That way we only have to worry about having two patterns - one when there is no data and one where the score is >= 0. 

As for the heatmap, do we have an example to test? When I look at the associations for BRAF (https://www.targetvalidation.org/target/ENSG00000157764/associations?view=t:table) and sort by the association score, even associations with a score of 0.00 have the blue background.
