### ISSUE TITLE
Text Mining: Text to highlight Target and Disease not always displayed

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/webapp#240]
### Observed behaviour
When looking at the Text Mining Evidence for the following Associations, for some PMIDs the text that contains Target and Disease is not displayed and therefore the items are not highlighted.

http://www.targetvalidation.org/evidence/ENSG00000174059/EFO_0002428
Papers: Nr. 2 (PMID: 28321124), Nr. 3 (28920959) and Nr. 5 (PMID: 29100302) - in these three examples the abstract stops mid-way through a sentence.

http://www.targetvalidation.org/evidence/ENSG00000091704/EFO_0000616
Papers: Nr. 3 (PMID: 28834963) and Nr. 4 (PMID: 28966012) - in these two examples the abstract also is cut-off mid-way through a sentence.

### Expected behaviour
Target and Disease highlighted.

### Environment
[How did you see the bug?]
* Version: on website
* Browser: Safari

**Comment by LucaFumis** [comment]
I think this is also due to a data issue.
The API response returns an incomplete (truncated) abstract.
The highlights are correct (text, start and end of T & D) as per `evidence.literature_ref.mined_sentences` but the text cannot be matched in the incomplete abstract.
Once again @ckongEbi or @mkarmona might have the answer?

**Comment by LucaFumis** [comment]
Moving issue to `data_pipeline` repo: https://github.com/opentargets/data_pipeline/issues/252
