### ISSUE TITLE
On evidence page 'RNA Expression' is greyed out even though there is data available

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/webapp#249]
### Observed behaviour
Using the OT platform with one of the examples (IBD) I noticed that on the association page for 'IL10RA in inflammatory bowel disease' the RNA Expression tab is greyed out even though there are 6 entries for IL10RA expression in IBD: https://www.targetvalidation.org/evidence/ENSG00000110324/EFO_0003767

### Expected behaviour
RNA Expression not be greyed out.

### Environment
[How did you see the bug?]
* Version: online
* Browser: Safari

**Comment by deniseOme** [comment]
And in addition to being greyed out on the evidence page, the associations page shows an empty row.

Another example:
https://www.targetvalidation.org/disease/EFO_0000196/associations?fcts=

![](https://files.slack.com/files-pri/T02UV853T-F9D8RADHT/screen_shot_2018-02-22_at_14.08.26.png)

@iandunham's suggested this may be because of the sensitivity correction that sets certain evidence to 0, which then isn't displayed in the heatmap (or greyed out in the evidence page) but it is available.

![](https://files.slack.com/files-pri/T02UV853T-F9CJF2T89/image.png)

**Comment by LucaFumis** [comment]
I can't reproduce the part @deniseOme highlighted above - the data has since changed and it seems to now work OK for me, for the same example

However there is a difference between associations and evidence pages.
On association pages, the heatmap takes into account evidence count: 
 - an empty cell shows "no data": score 0 + 0 evidence; 
 - a light blue cell shows score 0 + some evidence count.

This distinction is not taken into account on the evidence page, where the flower takes only association score (and hence the greyed out sections)
