### ISSUE TITLE
Pathways tab hanging

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/webapp#291]
### Observed behaviour
Pathways tab hangs indefinitely. After debugging, I noticed `otConsts.PROXY` was missing. Below is a screenshot from the public portal where it is **not** missing.

![image](https://user-images.githubusercontent.com/2900303/42218603-7781ec2e-7ec9-11e8-8b9e-f0f5651e39d8.png)
 
### Expected behaviour
`PROXY` environment should be accessible to the frontend.  I already checked `/var/www/app/config/consts/default.json` and the "PROXY" entry is there...so I don't know why it is not available to the frontend at runtime.

### Environment

* Version: latest image from `quay.io/opentargets/webapp` (from last week ~28th June)
* Browser: Chrome

**Comment by pieterlukasse** [comment]
@LucaFumis , @elipapa  any ideas on this one?

**Comment by elipapa** [comment]
not really sure. 
when i run the container with `docker run -d -p 8443:443 quay.io/opentargets/webapp`
I do get the proxy variable:

![image](https://user-images.githubusercontent.com/112610/42273653-aa67b48a-7f81-11e8-90d0-8579148cb2ce.png)

which is what I expect since the container composes the final `config.json` at build time. Are you changing other variables?

You should check the `/build/config.json` pathway in your deployment and see if the variable is there.

**Comment by pieterlukasse** [comment]
Thanks @elipapa! This helped me find the issue. I was running on an outdated `config.json`. After updating it (and making sure `PROXY` is in there) the pathways issue is gone.
