### ISSUE TITLE
same drug coming up several times

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#33]
This page shows one drug coming up several times. 
Why is that? Different targets? Can we add the target information as an extra column? https://www.targetvalidation.org/disease/EFO_0002609

In the case of DEXAMETHASONE, the information is the same, however, the evidence comes from different dailymed information:
http://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ce01733f-33b7-483e-9bc4-cf43937e6998
http://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=320747b3-5cf1-4e0c-b670-c6a9e72a8845

**Comment by peatroot** [comment]
This issue raises two points as I understand it, @gkos-bio:

* The drugs table shows one evidence string per row. This is consistent with evidence tables from other sources, but, in this case, a given drug may appear in multiple evidence strings. I would argue this is not an issue because evidence tables are consistently displayed this way in the `webapp`.
* An example of two evidence strings has been found (for DEXAMETHASONE) where all information is identical except the dailymed reference. This is a `data_pipeline` issue.

If I've not misunderstood, can I close this and raise the second point as a new issue in `data_pipeline`?

**Comment by emepyc** [comment]
This is an old known problem. The only difference in both entries is the dailymed link, but it is not displayed explicitly in the table (but implicitly in the dailymed link.
It has been suggested in the past that the those rows are collapsed and we provide 2 links for the same row. But at the same time it was also suggested to revise the evidence strings, this is why no action has been taken from the webapp point of view.

The other issue (showing the target) I think is relevant and can be easily fixed. Maybe passing a flag to the directive to tell it to display the target column or not.

**Comment by peatroot** [comment]
Thanks @emepyc. I'll expose the target in a column conditionally, so that the column only appears for the disease page. I agree that the other issue (two dailymed links) should be handled in `data_pipeline`, so will raise there.

**Comment by MichaelaEBI** [comment]
#261

**Comment by andrewhercules** [comment]
This issue has been resolved by exposing the target column in the drugs table. Also, with the planned introduction of a drug entity, the team can explore updating the data pipeline and revising the evidence strings so that rows are collapsed and we provide 1 or more links per row.
