### ISSUE TITLE
Overall association score labelling

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#47]
I wonder if it's useful to include the word "Overall" in the 2nd column in a page like https://www.targetvalidation.org/target/ENSG00000183072/associations?view=t:table

So instead of 'Association score' have 'Overall association score'? This will help users to realise the first column is the score for all the data types whereas the remaining columns the score is for each individual data type.

**Comment by emepyc** [comment]
Yes, I think we have had more users wondering what is the difference between the first column and the rest. I think part of the problem is that it is not easy to understand how the score is combined between the different data types to get the final score.
This is a very simple fix we can try.

**Comment by apierleoni** [comment]
Agree, I saw the sane confusion during the integration day workshop

19 feb 2017, 12:56 +0000, Miguel Pignatelli <notifications@github.com>, ha scritto:

**Comment by elipapa** [comment]
i would just drop this column @andrewhercules

**Comment by andrewhercules** [comment]
@elipapa: I agree - I think it causes confusion because users aren't sure what the first column means. And I wonder how many of them actually sort based on that column. In fact, I'd guess that users are more likely to sort based on another column (e.g. how strong is the drug evidence).  

It is likely that we will review the associations view as part of a broader look at creating a dashboard view and the search flow. Perhaps it will end up as a widget and if so, we'll have to think about what we show/hide.
