### ISSUE TITLE
Greying out tabs when there is no data for a given target

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#48]
We do grey out the tabs in the Evidence page (e.g. https://www.targetvalidation.org/evidence/ENSG00000065883/EFO_0000756).

I think it would be useful to have the same pattern for the Target profile page as well. E.g. Drugs here have no data but I need to click on the Tab to find that out. If it was grey, I'd have not bothered clicking on the tab. 

https://www.targetvalidation.org/target/ENSG00000065883

**Comment by andrewhercules** [comment]
Issue closed as feature request not possible due to technical constraints and the response from the API. With many of the tabs on the profile pages, the data is lazy loaded until the on-click action. As such, the webapp would not know if there is no data until the user has clicked the tab. That being said, a planned rewrite of the app and introduction of a dashboard would resolve this issue.
