### ISSUE TITLE
Genetic associations in the evidence page

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#54]
In a page like this:

https://targetvalidation.org/evidence/ENSG00000185551/EFO_0005207?view=sec:genetic_associations

The 3rd column is entitled "Gene-Disease Evidence Mutation consequence" and we have things such as 'missense variant' (which is a SO consequence term) but also 'curated variant' (which is not a SO consequence term).

I'd suggest have N/A instead of 'curated variant'. Ideally and better still it would be nice to run the VEP for that variant and report the consequence of it on the gene/transcript. We should have either the coordinates of the variant or its HGVS notation e.g.  C267Y at gene GDF (both accepted by the VEP).

**Comment by deniseOme** [comment]
I'd have thought the papers curated by UniProt will have the HGVS notation which most if not all cases will be a missense variant...

**Comment by iandunham** [comment]
The problem here is that one of these is true:
- there isn't a variant associated with the curated observation, which would be true of old data, or
- they haven't yet added a variant because they are catching up  - we could highlight cases where they
 know the variant, or
- the evidence is a summary across many variants. In some cases e.g. cystic fibrosis, there are both types of evidence from UniProt and we should ask them why they provide both if variants exist. 

![untitled](https://cloud.githubusercontent.com/assets/1729980/22024018/85e1efbe-dcc0-11e6-86c4-8eeaef23a045.png)

**Comment by emepyc** [comment]
have we agreed on any action on this?
If not, we should close this issue

**Comment by emepyc** [comment]
I'm closing this issue since no action has been agreed regarding this. If this needs to be addressed, please reopen it and comment.

**Comment by iandunham** [comment]
We will talk with Uniprot about their literature curated data, and how to add variants where they know them, or not duplicate @ckongEbi

**Comment by ckongEbi** [comment]
@iandunham meeting uniprot next week to find out more. 
@emepyc / @gkos-bio can this issue be moved to "data-providers-docs" ?

**Comment by emepyc** [comment]
Issue moved to [opentargets/data-providers-docs #29](https://github.com/opentargets/data-providers-docs/issues/29) via [**ZenHub**](https://www.zenhub.com/)
