### ISSUE TITLE
cannot interact with the mouse with bubble view

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#56]
i seem to be able to remember that you could click in and out of the bubble view to focus on a specific therapeutic area. that does not seem to be possible any more.

**Comment by emepyc** [comment]
This was removed long time ago in favour of using the therapeutic area facet on the left.
You probably miss that feature because you know it existed, but we are not sure if regular users would find it confusing or not, so we thought about investigating options with @nikiforosk 
We can't keep this open for now, but I have removed the "critical" label

**Comment by peatroot** [comment]
Given that the functionality was removed quite some time ago, it seems reasonable to close this.
