### ISSUE TITLE
Add punchline to the homepage

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#78]
Under 'Find new targets for drug discovery'
Add the following punchline:
Open Targets organises, evaluates, makes accessible and also contributes to the sources of human genomic evidence that are revolutionising how successfully targets can be identified and prioritised for the development of new and better medicines.

See benchling.com punchline for an example.

**Comment by emepyc** [comment]
Having the punchline would be great. I don't think under the "Find new targets for drug discovery" is the right place for it though. That sentence is coupled to the search bar. Placing a description of the platform in the middle is probably not right.
What about below the search bar?

**Comment by nikiforosk** [comment]
We redesigned the home page to show less text and make it more obvious what we offer through the content in the various sections. This was because people were not reading the text we had before.

The feedback we got from @elipapa contacts is that we are already showing too much information!

A punch line is a simple phrase. The proposed period is 35 words long, has 4 main verbs and two subordinate clauses. What does it actually say that we don't communicate already? Why do we need to add it?

Also it's about Open Targets not the platform per se so if anything it should go under the Open Targets section. 

If you can think of a snappier punch line (less than 10 words) that we can use to replace "Find new targets for drug discovery" let's consider this. But please don't add more text, especially text that doesn't add any meaningful content. My feeling that this punchline adds visual noise, and the ones bothered to read it will think "So what?"

**Comment by LucaFumis** [comment]
Some thoughts:

I agree a punchline could be both helpful and visually interesting.

That to me looks more of a punch-paragraph - it’s almost 2x longer than what benchling uses:
it could actually be long/substantial enough to get a section/block of its own, just under the blue block?

Discussing some user feedback yesterday with Niki and Eliseo it seemed that some users already find that part of the page somewhat “busy”, so a bit worried that adding more to it.

Benchling homepage is rather nice and simple - I like it

**Comment by emepyc** [comment]
I agree with @LucaFumis on this. There is room for a brief description of the platform, but I don't think that the proposed place is the right place for it.

**Comment by nikiforosk** [comment]
The other thing to consider here is that benchling are trying to get people to sign up so they are explaining their offerings upfront.

We want people to search for a gene or a disease. The home page should be motivating them to do their first search. Once they've done their first search it should be intuitively clear what the Platform is about and how it can help them. They can directly experience the site instead of reading about it.

I tried to explain this in the content model for the redesign of the home page: https://docs.google.com/presentation/d/1UV7rZryFa1yjLvNcGK5rlWL9KpYG_g4nX7CPSaEbj2Q/edit?usp=sharing
If you want to add content to the home page please consult this document first.

**Comment by elipapa** [comment]
+1 for under the search bar. What about adding another panel between the blue with the search box and the grey which gives _the_ numbers

regardless, i would suggest shorter copy. benchling is 20 words. the suggested one is ~35

**Comment by LucaFumis** [comment]
I tried a couple of mocks for this - I don't think I can attach them directly here, so will probably slack them.

**Comment by emepyc** [comment]
You can drag images directly in comments if you want, they get uploaded

**Comment by elipapa** [comment]
The sentence should be shorter. Split at the very least. Also the use of passive voice is not indicated in web copy. 

![image](https://cloud.githubusercontent.com/assets/112610/23175325/f0dcfdd4-f856-11e6-97cb-b7b6e8386510.png)

**Comment by apierleoni** [comment]
Will not do until a better shorter sentence is proposed.

**Comment by elipapa** [comment]
My suggestions: 

>Search for a disease and learn which are the most promising genomic targets for new medicines.

and

>We combine over 2.5 millions data points from 13 public biological databases.
