### ISSUE TITLE
2.10 tag does not contain express module as a dependency

### ISSUE THREAD

**Issue by dorkosaurus** [opentargets/webapp#95]
I had to run npm install express separately to get this to work.

**Comment by emepyc** [comment]
Hmm, I may be missing something but we don't depend on express. Why did you have to install it?

**Comment by dorkosaurus** [comment]
When I run `npm start`, it calls `cd server && node server.js` 

server.js contains this on the first line:

```
var express = require("express");
```

**Comment by emepyc** [comment]
Ah, ok. At some point we developed a minimal node server that was replaced at some point by a nginx run inside a docker container. The node server is not supported anymore and we should have cleaned it (we keep it there for reference, but it is no longer mentioned in any documentation). You probably discovered `npm start` just looking at the scripts appeared at the `package.json`, if you found it as part of the instructions somewhere, let us know because it shouldn't be referenced.

The preferred way to run this application is by running the docker container. If you need any further assistant for that, please get in touch.

**Comment by dorkosaurus** [comment]
Okay thanks!

**Comment by emepyc** [comment]
No problem, feel free to reopen if you require any further clarification
